name: Build release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build -rv
    #- name: Dry run
      #run: ./target/release/oscar -d
    - name: Save binary
      uses: actions/upload-artifact@v3
      with:
        name: oscar-${{ matrix.os }}
        path: ./target/release/oscar
